services:
  db:
    image: mariadb:10.9
    environment:
      MARIADB_ROOT_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql

  web:
    # imageの記述がない代わりに現在のディレクトリに存在するDockerfileをもとにイメージを作る。
    build: .
    depends_on:
      - db
    environment:
      DATABASE_PASSWORD: password
    ports:
      - "3000:3000"
    volumes:
      - .:/ruby_app
volumes:
  db-data:
